services:
  redis:
    image: redis:7.4-alpine
    command: redis-server --appendonly yes --appendfsync everysec --requirepass password
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis/:/data/
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
